import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by Next.js
    "src/shared/types/validator.ts",
    "src/shared/types/routes.d.ts",
    "src/shared/types/cache-life.d.ts",
    // Third-party type declarations
    "src/swagger-ui-react.d.ts",
    // Generated coverage reports
    "coverage/**",
  ]),
  // Relaxed rules for test files
  {
    files: ["__test__/**"],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unused-expressions": "off",
    },
  },
]);

export default eslintConfig;
