sonar.projectKey=eatryp
sonar.projectName=Eatryp
sonar.language=ts
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=\
  src/app/**,\
  src/**/*.d.ts,\
  src/**/validator.ts,\
  src/**/swagger.ts,\
  src/**/Gruposanimados.tsx,\
  src/**/types/**,\
  src/**/api/**,\
  src/**/I*.ts,\
  src/**/IDatabaseService.ts,\
  src/**/components/**

sonar.tests=__test__
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverageReportPaths=coverage/cobertura-coverage.xml

sonar.typescript.tsconfigPath=tsconfig.json
sonar.typescript.exclusions=**/node_modules/**,**/*.test.ts
