sonar.projectKey=LPC
sonar.projectName=LPC
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=\
  **/node_modules/**,\
  **/*.d.ts,\
  src/app/**,\
  src/**/types/**,\
  src/**/components/**,\
  src/**/Gruposanimados.tsx,\
  src/**/swagger.ts

sonar.coverage.exclusions=\
  src/**/*.d.ts,\
  src/**/validator.ts,\
  src/**/swagger.ts,\
  src/**/Gruposanimados.tsx,\
  src/**/types/**,\
  src/**/I*.ts,\
  src/**/IDatabaseService.ts,\
  src/**/components/**,\
  src/app/**

sonar.tests=__test__
sonar.test.inclusions=**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.typescript.tsconfigPath=tsconfig.json
sonar.host.url=https://sonarqube.inf.uct.cl
sonar.token=sqp_8d096a8cf148bed980c30ed070f746d26b1def03